### PR TITLE
Add description for JSON parsers

### PR DESCRIPTION
**Pull request by splashinn**
Thanks for contributing to the Ruby Toolbox catalog! <3

**Before submitting your pull request:**

- [x] If you are submitting a github-based project, please verify the project is not packaged as a rubygem
- [x] Please make sure the projects are listed in alphabetical order
- [x] Make sure the CI build passes, we validate your proposed changes in the test suite :)

### CODE REVIEW

**Comment by colszowka** [comment]
Thanks for your contribution @splashinn !

I think JSON parsing goes beyond parsing data from a web server, and also usage goes beyond displaying this data in web pages immediately.

Taking some inspiration from https://en.wikipedia.org/wiki/JSON, how about: "JSON parsers convert data serialized in the popular JSON data exchange format to and from Ruby objects"?

**Comment by splashinn** [comment]
@colszowka I agree, thank you for making the description better!

**Comment by splashinn** [comment]
@colszowka I updated the JSON parsers per your request; just checking if there's anything else you'd like me change in regards to this PR

**Comment by colszowka** [comment]
@splashinn Thanks for your time, and sorry for the slow feedback, it's summer time... :sun_with_face: :swimming_man: ;) Good to go, merging!

**Pull request merged**
