### PR TITLE
Add OCR category with Tesseract bindings

### PR DESCRIPTION
**Pull request by arbox**
Thanks for contributing to the Ruby Toolbox catalog! <3

**Before submitting your pull request:**

- [x] If you are submitting a github-based project, please verify the project is not packaged as a rubygem
- [x] Please make sure the projects are listed in alphabetical order
- [x] Make sure the CI build passes, we validate your proposed changes in the test suite :)

Doing first small steps.

Refer rubytoolbox/rubytoolbox#8.

### CODE REVIEW

**Comment by colszowka** [comment]
@arbox Thanks a lot. I would suggest to adjust the description to be a bit more generic, so it remains fitting if an OCR library shows up that is not using tesseract etc.

Would "Libraries to extract text from images" work?

**Comment by arbox** [comment]
@colszowka 
Hm, what do you mean? The name for PR reflects exactly what it does (adding Tesseract bindings _as a first step_). As suggested in rubytoolbox/rubytoolbox#8, the group is called `Natural Language Processing` and the category `Optical Character Recognition` (which is an established way to call extracting texts from images). `OCR` does not automatically mean `tesseract`. Or do I understand you wrong?

**Comment by arbox** [comment]
@colszowka Frohes neues!
How do we want to proceed?

**Comment by colszowka** [comment]
Hey @arbox, danke gleichfalls :)

I was referring to the description you put on the category.yml itself, `description: Use (mostly) external tools to recognize written text from image data` - while tesseract is an external tool, existing or future tools that we add to the category might be written in ruby or as a c-ext, so I would propose we widen the scope of the description and put something broader like "description: Libraries that extract text from images", all ready to merge otherwise :)

**Comment by arbox** [comment]
@colszowka please look at the changes and feel free to merge.
I'll continue working on the NLP Category.

**Comment by colszowka** [comment]
@arbox Perfect, thank you!

**Pull request merged**
