### PR TITLE
Adding LegionIO to Background Jobs and Scheduling

### PR DESCRIPTION
**Pull request by Esity**
LegionIO is an extensible framework for connecting and scheduling tasks. 
Let me know if you any any questions

### CODE REVIEW

**Comment by Esity** [comment]
Hey @colszowka Sorry for the ping, is there anything else I need to do for review on this one?

**Comment by colszowka** [comment]
@Esity Is this meant for public consumption? Because I could find only very little information on the readme and the links towards it why I would want to use this - how does it help me? How would I use it in Ruby? Could you please update the readme accordingly with some details so visitors to the source can get a glimpse of what this is for? Thanks!

**Comment by Esity** [comment]
@colszowka sorry for the delay. That time of the year!

Yeah, it could be potentially something that a person would want to use. It's just a connector of things, almost like an IFTTT. I have put most of the info on the confluence pages but I will update the README to have more info so people don't have to click through to multiple pieces

Here is the overview page
https://legionio.atlassian.net/wiki/spaces/LEGION/overview

Here is a list of the extensions that are either available or being worked on
https://legionio.atlassian.net/wiki/spaces/LEX/pages/7864551/Extensions

**Comment by Esity** [comment]
@colszowka 

I have updated the README to actually say what it does with examples and it lists some of the available extensions you can use. Let me know if you want me to add/update anything else

**Comment by Esity** [comment]
@colszowka  any additional feedback or conditions for merging?

**Comment by Esity** [comment]
Just wanted to check in @colszowka let me know what's needed

**Comment by colszowka** [comment]
@Esity Sorry for the delay, I didn't have much time to check out the PRs here on the catalog recently :/ I think the overview info on the README is fine now, however I noticed that the gem description itself is still "Legion Core runs Legion Framework", which does not tell me anything, and would be basically the [only thing displayed once the project is actually in the category](https://www.ruby-toolbox.com/projects/legionio), which I don't think would be sufficient to help people identify this library might help them. 

Could you please update the gem description with something that when browsing the background jobs category would help understand the purpose of the gem without having to go over to the bitbucket repository? For example, sidekiq has "Simple, efficient background processing for Ruby.". Thanks!

**Comment by Esity** [comment]
I am currently in the process of migrating the code base from Bitbucket to GitHub.com/Optum

Will update this PR when completed. Also I updated the descriptions per your request but am waiting to deploy until after we move the repos

**Comment by Esity** [comment]
@colszowka 

Thanks for the patience on this one. We have moved this repo as @Optum is taking over the repos(I work for Optum) so that it can be published under our name. Still open sourced, still meant for public consumption. 

I did update the gem description and a few other things. Let me know if you need anything else for a merge!

**Comment by Esity** [comment]
@colszowka Is something we can merge now?

**Pull request merged**
