### PR TITLE
Promote the category "API Clients"

### PR DESCRIPTION
**Pull request by FranklinYu**
Closes rubytoolbox/rubytoolbox#131.

### CODE REVIEW

**Comment by franklinyu** [comment]
Bump.

**Comment by franklinyu** [comment]
Is this pull request blocked by anything?

**Comment by colszowka** [comment]
@franklinyu Very sorry for the delayed response! Could you please undo the rename on the api_clients.yml file? That would break the permalink on that category :) Thanks!

**Comment by franklinyu** [comment]
How about its content? Keep the new name or not?

**Comment by colszowka** [comment]
Yeah, keep it as "other", it's just that the permalink must remain so that 
existing links are pointing *somewhere* :) Thanks!

**Comment by franklinyu** [comment]
Sorry for this long delay. I’m still wondering: if I keep the filename for `/catalog/Web_Apps_Services_Interaction/api_clients.yml`, how does the system know that it belongs to major category “HTTP API Clients”?

**Comment by colszowka** [comment]
@franklinyu Thanks for getting back

* The filename 'api_clients.yml' maps to the category URL https://www.ruby-toolbox.com/categories/api_clients - therefore it should not change
* The display name of the category can indeed change to "Other Clients" so we can split out common clients into their own categories
* Since the category group (the folder name) is not part of the category url, it does not affect the permalink to the category (https://www.ruby-toolbox.com/categories/api_clients)

**Comment by franklinyu** [comment]
Oh, I misunderstood you. So you actually mean `/catalog/HTTP_API_Clients/api_clients.yml`?

**Comment by franklinyu** [comment]
This is ready for merge.

**Comment by franklinyu** [comment]
@colszowka Bump.

**Comment by colszowka** [comment]
Thanks @FranklinYu! Finally merged this :snail:

**Comment by FranklinYu** [comment]
Awesome! Now I can start working on #89. Will ping you when I finish. Thank you for your work!

**Comment by colszowka** [comment]
@FranklinYu Awesome, thanks! Didn't see your comment before mentioning you on the other PR, thanks a lot for looking into it :)

**Pull request merged**
