### PR TITLE
Add some gems

### PR DESCRIPTION
**Pull request by westonganger**

### CODE REVIEW

**Comment by colszowka** [comment]
Thanks! 

"Rails extensions" seems quite broad, can we find a slightly more descriptive name? Also, do you know similar libraries so we have at least two projects in that category?

**Comment by westonganger** [comment]
I was just following the convention provided by Ruby Core Extensions. Would it be better to call it Rails Core Extensions. I don't know of any other libraries, most similar libraries usually have to do with ActiveRecord only, mine patches both Rails & ActiveRecord.

**Comment by colszowka** [comment]
@westonganger Yeah, I also thought of Ruby Core Extensions, but that one has a bit more of a tradition in the ruby community by means of `active_support/core_ext`

Let's leave it as-is, once the category is there maybe someone else will chip in and suggest more projects for this :)

**Comment by colszowka** [comment]
@westonganger One more thing, could you please provide a description for the new category? I know most of the existing ones do not have one either, but I'd like to add them over time :)

**Comment by westonganger** [comment]
Okay I have now added the description for the Rails Extensions category.

**Comment by colszowka** [comment]
Thanks

**Pull request merged**
