### PR TITLE
Add ForestAdmin to the rails_admin_interfaces

### PR DESCRIPTION
**Pull request by SeyZ**
Thanks for contributing to the Ruby Toolbox catalog! <3

**Before submitting your pull request:**

- [x] If you are submitting a github-based project, please verify the project is not packaged as a rubygem
- [x] Please make sure the projects are listed in alphabetical order
- [x] Make sure the CI build passes, we validate your proposed changes in the test suite :)

### CODE REVIEW

**Comment by SeyZ** [comment]
Hey, I'm not sure what do you mean by the first item on the checklist:
If you are submitting a github-based project, please verify the project is not packaged as a rubygem

Can you clarify exactly the purpose of this?

**Comment by BookOfGreg** [comment]
The meaning is if you are about to submit a GitHub repository, check it isn't already a gem as gems are preferred.

**Comment by SeyZ** [comment]
Thanks @BookOfGreg ! I've edited the name to `forest_liana` 👍

**Comment by BookOfGreg** [comment]
Thank you @SeyZ for contributing 👍 Looks like an interesting gem.

**Comment by SeyZ** [comment]
On average, how much time does it take for a PR to be merged? Thanks!

**Comment by BookOfGreg** [comment]
I've seen @colszowka around GitHub a week or two ago, I tend to get notifications in waves so he will probably merge all PRs at once. Don't worry, I don't see any reason this wouldn't be merged when he next does a wave.

**Comment by SeyZ** [comment]
Thanks for the update @BookOfGreg 👍

**Comment by colszowka** [comment]
Hey @SeyZ, sorry for the delay. Merging now!

I would urge you to add some additional references to your gemspec, i.e. the homepage url and the source code url. See https://github.com/jeremyevans/roda/pull/157 for an example of the latter. As it stands if somebody sees your gem on the toolbox it does not link to your service, it does not link to the source code repo and you're missing all the github stats. If you add the repo reference it should be picked up by the toolbox automatically

**Pull request merged**
