### PR TITLE
Add some gems.

### PR DESCRIPTION
**Pull request by phlegx**
I have tried to fit some of our gems in the available categories.

1. **macker** - Real MAC addresses generator and vendor lookup with MAC address handling.
2. **redlics** - Redis analytics with tracks (using bitmaps) and counts (using buckets).
3. **money-currencylayer-bank** - A gem that calculates the exchange rate using published rates from currencylayer.com. Compatible with the money gem.
4. **money-openexchangerates-bank** - A gem that calculates the exchange rate using published rates from openexchangerates.org. Compatible with the money gem.
5. **hiredis**  - Ruby wrapper for hiredis (protocol serialization/deserialization and blocking I/O)
6. **readthis** - Pooled active support compliant caching with redis
7. **sentry-raven** - A gem that provides a client interface for the Sentry error logger
8. **ipaddress** - IPAddress is a Ruby library designed to make manipulation of IPv4 and IPv6 addresses
9. **maxminddb** - Pure Ruby MaxMind DB (GeoIP2) binary file reader.
10. **globalize-accessors** - Define methods for accessing translated attributes
11. **route_translator** - Translates the Rails routes of your application into the languages defined in your locale files

### CODE REVIEW

**Comment by colszowka** [comment]
Thanks @phlegx 

Regarding macker, I'm not sure whether that fits into security tools. Isn't this more related to networking in general?

**Comment by phlegx** [comment]
@colszowka yes sir.

**Comment by colszowka** [comment]
@phlegx Would you mind dropping macker from the security tools category then, and maybe create a "Networking Tools" category? From the existing groups, either "Developer Tools" or "Maintenance and Monitoring" seem to fit best, but I'm not sure, maybe something else would work better?

Also, if you can think of other tools to add to said new networking category, please add them too :)

**Comment by colszowka** [comment]
Perfect, thanks!

**Pull request merged**
