### PR TITLE
Add Avo to a few other categories

### PR DESCRIPTION
**Pull request by adrianthedev**
Thanks for contributing to the Ruby Toolbox catalog! <3

**Before submitting your pull request:**

- [x] If you're referencing a gem by its GitHub repository (e.g. `rails/rails`), please verify
      that it is _not_ packaged as a Ruby gem. (If it _is_ packaged as a gem, please reference it
      by its gem name instead, e.g. `rails`.)
- [x] Please make sure the projects are listed in case-insensitive alphabetical order
- [x] Make sure the CI build passes, we validate your proposed changes in the test suite :)

### CODE REVIEW

**Comment by colszowka** [comment]
@adrianthedev Thanks - however I'm not sure it makes sense to add avo to these as AFAIK it's more general purpose and while you can use it to make a CRM or CMS, the way I understand is it doesn't offer these things out of the box to just put on a server and run - please correct me if I'm wrong! But in such a case, we could put rails and sinatra in all these categories too because you can also use them to make a CMS

For the table builders, it also seems not really fitting, or do you have a feature where you can solely use some functionality avo offers to more easily build some datagrid table into your existing rails app UI?

**Comment by adrianthedev** [comment]
Hey @colszowka.
Thanks for replying.

Avo is really a very powerful CMS builder. I think when we think about CMSs we think about Wordpress and having "posts" and "pages" with comments attached, but the content can actually be anything and the power of a CMS comes with the customization options. 
The content can be very varied and Avo supports managing it very well :)
It doesn't take much to add "posts" and "pages", and similarly it doesn't take much to add "orders", "customers", "products", or any other type of content.

Avo is on a different level than Rails or Sinatra on creating things CMSs.

I'm not adding this just by my own desire, but I've had users [recommend this](https://discord.com/channels/740892036978442260/1039573545828753438/1194232758730498128).

CleanShot 2024-01-12 at 13 38 07@2x


I get it with table builders and CRMs, and removed it from those categories.

I appreciate your curation and think that Avo deserves to be in the CMS category too.

**Comment by colszowka** [comment]
@adrianthedev Thanks for the quick reply and your explanation, I'm on a high level familiar with the project but not enough to really make a call on this, but based on your explanation it makes sense to me to do it like that. Thanks & happy friday!

**Comment by adrianthedev** [comment]
Thank you @colszowka!

If you ever need to get more familiar, on a work or side project, please get in touch with me.
I'd love to show you more.

**Pull request merged**
