### PR TITLE
Added DRG CMS

### PR DESCRIPTION
**Pull request by drgcms**
My humble addition to Ruby Toolbox.

### CODE REVIEW

**Comment by colszowka** [comment]
Thanks! However, instead of creating a separate category with just one project it'd be better to add it to existing. By the project descriptions, I'd suggest adding it to these two:

* https://www.ruby-toolbox.com/categories/social_networking
* https://www.ruby-toolbox.com/categories/content_management_systems

Thanks!

**Comment by drgcms** [comment]
More proper category would be Rapid Web Application Development. I think social networking is not suitable. I removed Intranet development tools category. 

by
TheR

**Comment by colszowka** [comment]
Cool, thank you!

If this is similar to tools like [hobo](https://www.ruby-toolbox.com/projects/hobo) please add the suggested rapid app development category in a followup PR.

**Comment by drgcms** [comment]
If I understand you correctly you are suggesting that I made new
rapid_app_development category in

Web_Apps_Services_Interaction folder and add hobo and drg_cms to it.


by

Damjan Rems

2018-03-10 20:50 GMT+01:00 Christoph Olszowka <notifications@github.com>:

**Pull request merged**
