### PR TITLE
Gtk3 and other gems

### PR DESCRIPTION
**Pull request by cedlemo**
cc@kou

### CODE REVIEW

**Comment by colszowka** [comment]
Thank you @cedlemo!

Regarding the GUI Frameworks category, I'm not sure if all these low-level lib bindings fit very well in there. Generally, the category is meant for full-blown frameworks for building GUI-based applications, maybe it would be better to split out the low-level components specific to the Gnome world to a separate category?

**Comment by cedlemo** [comment]
Of course, so I should just let 

- gtk3, vte, vte3, gtksourceview, gtkwebkit, goffice and gnumeric in the GUI category.

Why not create a Gnome subcategory in Developer tools ?

There are of lot of libs in the Ruby-GNOME2 project.

**Comment by colszowka** [comment]
I'm not familiar enough with all of these, as a rough guideline I'd say the libraries should give you some joint utilities for window / layout management and ui widgets, so for example gtk3 would in my opinion fit very well, vte probably not. But since you seem familiar with the topic, please decide :)

Yes, a gnome category in dev tools sounds great!

Thanks!

**Comment by cedlemo** [comment]
Both vte, vte3, gtksourceview, gtkwebkit, goffice and gnumeric are specific widgets to be used with Gtk3. For example when you want to create a terminal, you use vte3 that loads as a dependency Gtk. In the same way if you want to create a code editor, you use gtksourceview, you want to create a browser in Gtk3, you use gtkwebkit and it is the same with gnumeric and goffice.

Here is a little terminal with vte : 
* https://github.com/ruby-gnome2/ruby-gnome2/blob/master/vte/sample/terminal.rb

or a browser with webkit2:
* https://github.com/ruby-gnome2/ruby-gnome2/blob/master/webkit2-gtk/sample/browser.rb

Tell me if with this examples you agree that I let those libs in the GUI part.

> gnome category in dev tools sounds great!

Nice I will do another clean PR. Tell me if with this examples you agree that I let those libs in the GUI part.

**Comment by colszowka** [comment]
Than for the detailed input! If those are specific to gtk, I'd personally keep them out of the frameworks category, but a dedicated category seems very fitting.

I'd personally also just update this PR, but whatever works best for you! Thanks for your efforts!

**Pull request closed without merging**
