### PR TITLE
ruby_version_management: add ruby-install, remove rbfu

### PR DESCRIPTION
**Pull request by mediafinger**
Adds `ruby-install` which is from the same author as `chruby` and works well together with it.

Removes `rbfu` as @hmans deprecated it in the favor of `chruby` some years ago.

---

- [x] We should ask @phoet if it's worth to keep the `which-ruby` gem around?

---

- [x] @colszowka personally I would keep those lists alphabetically sorted. Apart from an initially higher chance of merge conflicts, is there anything why you would not want to do that?

### CODE REVIEW

**Comment by phoet** [comment]
please remove it if that helps

**Comment by mediafinger** [comment]
I read your comment here: and sorted the list alphabetically.

I also added the missing user names (rvm -> rvm/rvm) to make it more consistent.

And finally removed `vertiginous/pik` as it is unmaintained. They suggest to use: https://bitbucket.org/jonforums/uru - but as that is not hosted on GitHub, I assume there is no point in adding at at the moment. I could add it as a comment, if wanted.

**Comment by colszowka** [comment]
@mediafinger Thanks!

I wonder however, how to deal with deprecated / unmaintained project. As it stands if we simply remove a project from the category, we "lose information", i.e. the acknowledgement that this project exists and fits into this category. For example, I'd imagine the possible situation that a project is unmaintained, but somebody still finds it useable or even would like to pick it up as maintainer? 

Maybe it would be better to keep those projects in the category and flag deprecations / maintainership in a centralized "deprecations.yml" list, referencing projects by their rubygem/github ref? We could then clearly flag those projects in the UI while retaining information. Note: This topic has overlap with https://github.com/rubytoolbox/rubytoolbox/issues/7

**Comment by mediafinger** [comment]
@colszowka yes, interesting thought. Though some projects are so clearly outdated (and have worthy or even better successors) that I think it would be fine not to clutter the catalog with them.

**Comment by colszowka** [comment]
@mediafinger Personally I think I'd still rather keep those projects around and flag them clearly in the UI. Otherwise we will have to set up a whole framework of "what is the recommended replacement? why is this the recommended replacement (original mantainer? community fork?)". The Ruby Toolbox's take on "recommending" projects was always to give developers a reasonable overview do decide themselves.

Regardless, I would suggest to:

* Keep the removed projects around in this PR (maybe add comments and a reference to https://github.com/rubytoolbox/rubytoolbox/issues/7 in the YAML?)
* Take this discussion over to https://github.com/rubytoolbox/rubytoolbox/issues/7 and find some agreement there
* Update the category according to that outcome

It would probably also make sense to ultimately document these categorization guidelines (i.e. also from https://github.com/rubytoolbox/rubytoolbox/issues/3) into a `CONTRIBUTING.md` in this repo.

What do you think?

**Comment by hmistry** [comment]
@colszowka I agree with you in keeping deprecated/unmaintained projects around. I think there is value in that because everyone's needs are different and it would be nice to discover alternatives that maybe a simple yet ideal solution even though its unmaintained or deprecated.

**Comment by mediafinger** [comment]
For my taste, projects that:
- have been deprecated in favor of a successor some years ago
- are outdated and unmaintained for many years
add only noise to the catalog.

If something is just unmaintained for some years, or only deprecated for a year or two, I can understand that the project could still serve as a source of inspiration.

---

Anyway, I re-added the outdated projects and some comments in the line above them.

If you want to have a parsable version of this, we would have to add a new category, something like this:

```yaml
name: Ruby Version Management
description:
projects:
  - postmodern/chruby
  - postmodern/ruby-install
  - rvm/rvm
  - senny/rvm.el
  - sstephenson/rbenv
  - sstephenson/ruby-build
outdated_projects:
  - hmans/rbfu
  - phoet/which_ruby
  - vertiginous/pik
```

**Comment by colszowka** [comment]
@mediafinger Thanks! As I said, if we keep the projects in the catalog we retain the information and can decide later what to do with it (for example: not display those projects on the site, give them a separate "deprecated" sidebar or something like that.

FWIW for example pik being unmaintained also carries information about the adoption ruby development windows is getting :) Also, if we drop the projects altogether from the categories, at some later point someone might "accidentally" add them back in, so maybe that wouldn't be all that helpful :)

What do you think about adding a `deprecations.yml` in something like this structure?

```
"hmans/rbfu": 
  reason: Deprecated by author
  replacement: postmodern/chruby
cancan: 
  reason: Maintenance by original author ended
  replacement: cancancan
```

**Comment by mediafinger** [comment]
@colszowka IMO the `deprecations.yml` should retain the category information.
So when going for one file for the whole catalog, we should add the category hierarchy in there (in this case: `Developer Tools` -> `Ruby Version Management`).

**Comment by colszowka** [comment]
@mediafinger We can infer the category information from the category yml itself (I will soon get started on building the tooling for validating and converting this index into a JSON that will then be used by the app), so this would duplicate the information and create extra maintenance effort. Also, projects can now be put into multiple categories, so that would break this. But mostly, I would keep the redundancy out of the catalog and just infer/map this at catalog build time :)

**Comment by mediafinger** [comment]
Ok, now I get your idea. You want to add the projects additionally to the `deprecations.yml`.

Then I would suggest to merge this PR (the comments should not influence the parsing) and plan the structure for the `deprecations.yml` and where it should live separately.

**Pull request merged**
