### PR TITLE
bitfield_attribute added

### PR DESCRIPTION
**Pull request by gzigzigzeo**

### CODE REVIEW

**Comment by pboling** [comment]
Nice addition!
What is the reason for removing the alternative gem [bitmask_attributes](https://rubygems.org/gems/bitmask_attributes) (and on [github](https://github.com/joelmoss/bitmask_attributes))?

**Comment by gzigzigzeo** [comment]
Oh, I am sorry, have I? Looks I removed it by mistake. Will add back now.

**Comment by gzigzigzeo** [comment]
Sorry again, added back and cleaned up commit history.

**Comment by colszowka** [comment]
Thanks!

**Pull request merged**
