### PR TITLE
add OpenDocument related tools

### PR DESCRIPTION
**Pull request by noraj**
Thanks for contributing to the Ruby Toolbox catalog! <3

**Before submitting your pull request:**

- [x] If you're referencing a gem by its GitHub repository (e.g. `rails/rails`), please verify
      that it is _not_ packaged as a Ruby gem. (If it _is_ packaged as a gem, please reference it
      by its gem name instead, e.g. `rails`.)
- [x] Please make sure the projects are listed in case-insensitive alphabetical order
- [x] Make sure the CI build passes, we validate your proposed changes in the test suite :)

### CODE REVIEW

**Comment by noraj** [comment]
There is an issue with long gem name

eg. this gem is 62 char long https://rubygems.org/gems/chupa-text-decomposer-libreoffice-office-open-xml-presentation

Causing this issue on the CI https://github.com/rubytoolbox/catalog/pull/559/checks?check_run_id=2804023582

Because the schema doesn't support items longer than 50 chars https://github.com/rubytoolbox/catalog/blob/main/json-schema.yml#L54

**Comment by colszowka** [comment]
@noraj Interesting, I didn't even know such long names were possible :) Thanks for pointing it out, I'll take a look soon!

**Comment by noraj** [comment]
> @noraj Ok, finally got around to look in to this - the limit is now increased. Could you please rebase your branch and push again? Thanks!

✅ Done

**Comment by colszowka** [comment]
Thank you, and sorry for the long wait!

**Pull request merged**
