### PR TITLE
Add rb and rexe tools to a new Command Line Utilities section. 

### PR DESCRIPTION
**Pull request by keithrbennett**
Create a new CommandLineUtilities section in Developer_Tools, and add the following to it:

* https://github.com/thisredone/rb
* https://github.com/keithrbennett/rexe

### CODE REVIEW

**Comment by colszowka** [comment]
@keithrbennett Thanks! I'm not 100% sure the category name is descriptive enough though, the way it is it's very generic. I don't have a better suggestion though, really. Let's see if we can come up with something a bit more specific, otherwise let's merge it as is

**Comment by keithrbennett** [comment]
I agree. I struggled to come up with a good name. Command Line Filters & Executors would be more precisely suited to these 2 utilities, but I thought might be too narrow a category, and would end up only with these 2. How about "Shell Utilities"?

**Comment by BookOfGreg** [comment]
Just took a look at both of the tools listed. I'd definitely find them under the word 'utilities' if I was looking.
What's the generic term for tools like 'ls' or 'sed/awk'? That might help us on naming.

The `rb` one is especially neat so thanks for helping me discover that one.

**Comment by colszowka** [comment]
Hm, I still have no better suggestion than the existing one - let's merge this as is :)

**Pull request merged**
